name: train_deploy
on:
 push:
  branches : main
 workflow_dispatch:

jobs:
  train-and-evaluate:
   runs-on: ubuntu-latest
   steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set-up-python
      uses: actions/setup-python@v4
      with:
       python-version: "3.10"
    - name: install dependences
      run: |
       python -m pip install --upgrade pip
       python -m pip install -r  requirements.txt
  
    - name: train and save the model the model
      run:
       python scripts/model.py
   
    - name: deploy model
      env:
        HF_TOKEN: ${{secrets.HF_TOKEN}}
      run: python scripts/deploy.py
  
    - name: install email dependences
      run: |
       python -m pip install secure-smtplib
    - name: send mail
      env:
       SMTP_SERVER: ${{secrets.SMTP_SERVER}}
       SMTP_PORT : ${{secrets.SMTP_PORT}}
       EMAIL_SENDER: ${{secrets.EMAIL_SENDER}}
       EMAIL_RECEIVER: ${{secrets.EMAIL_RECEIVER}}
       EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
       
      run: python scripts/send_email.py

  




